server:
  port: 9005
spring:
  application:
    name: server-producter
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db1?serverTimezone=GMT%2B8
eureka:
  client:
    service-url:
      defaultZone: http://node1:8001/eureka/,http://node2:8002/eureka/，http://node3:8003/eureka/
mapper:
  mappers: com.it.mapper.TkMapper
  identity: MYSQL
mybatis:
  mapper-locations: classpath*:mapper/*.xml
logging:
  level:
    com.it: debug